name: "Suggestion"
description: "Soumettre une suggestion de pensée positive à ajouter au widget."
title: "[Suggestion] "
labels: ["suggestion", "triage"]
assignees:
  - batirunchalet

body:
  - type: markdown
    attributes:
      value: |
        Veuillez proposer une pensée courte, positive et non offensive.
        Merci pour votre contribution.

  - type: textarea
    id: pensee
    attributes:
      label: Ma suggestion
      description: "Que proposez-vous?"
      placeholder: "Ex.: Je progresse un peu chaque jour."
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: Auteur (facultatif)
      description: "A qui attribuer cette suggestion?"
      placeholder: "Anonyme"
    validations:
      required: false

  - type: checkboxes
    id: droits
    attributes:
      label: Confirmation
      description: "Requis."
      options:
        - label: "Je confirme que ma suggestion est positive et non offensive."
          required: true
